from jinja2 import Template
from xhtml2pdf import pisa
from datetime import datetime
import os

def generate_soap_note_pdf(data):
    html_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>SOAP Note</title>
        <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1, h2 { color: #2c3e50; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ccc; padding: 8px; }
            th { background-color: #f5f5f5; }
            .section { margin-bottom: 30px; }
            .footer { margin-top: 40px; font-size: 0.9em; color: #888; text-align: center; }
        </style>
    </head>
    <body>
        <h1>SOAP Note</h1>
        <div class="section">
            <h2>Patient Details</h2>
            <p><strong>Name:</strong> {{ patient_name }}</p>
            <p><strong>Age:</strong> {{ age }}</p>
            <p><strong>Gender:</strong> {{ gender }}</p>
            <p><strong>Visit Date:</strong> {{ visit_date }}</p>
            <p><strong>Chief Complaint:</strong> {{ chief_complaint }}</p>
        </div>
        <div class="section">
            <h2>Symptoms</h2>
            <p>{{ symptoms }}</p>
        </div>
        <div class="section">
            <h2>Diagnosis</h2>
            <p><strong>Primary:</strong> {{ primary_dx }} (ICD-10: {{ icd_code }})</p>
            <p><strong>Secondary:</strong> {{ secondary_dx }}</p>
        </div>
        <div class="section">
            <h2>Prescription</h2>
            <table>
                <tr>
                    <th>Drug</th>
                    <th>BF/AF</th>
                    <th>Morning</th>
                    <th>Afternoon</th>
                    <th>Night</th>
                    <th>Total Qty</th>
                </tr>
                {% for drug in prescribed_drugs %}
                <tr>
                    <td>{{ drug }}</td>
                    <td>{{ bfaf[drug] }}</td>
                    <td>{{ dosage_schedule[drug][0] }}</td>
                    <td>{{ dosage_schedule[drug][1] }}</td>
                    <td>{{ dosage_schedule[drug][2] }}</td>
                    <td>{{ quantity[drug] }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="section">
            <h2>Prognosis</h2>
            <p>{{ prognosis }}</p>
        </div>
        <div class="footer">
            Generated by Dr. {{ doctor_name }} on {{ today }}
        </div>
    </body>
    </html>
    """

    template = Template(html_template)
    html = template.render(
        patient_name=data.get("patient_name", ""),
        age=data.get("age", ""),
        gender=data.get("gender", ""),
        visit_date=data.get("visit_date", ""),
        chief_complaint=data.get("chief_complaint", ""),
        symptoms=data.get("symptoms", ""),
        primary_dx=data.get("primary_dx", ""),
        icd_code=data.get("icd_code", ""),
        secondary_dx=data.get("secondary_dx", ""),
        prescribed_drugs=data.get("prescribed_drugs", []),
        bfaf=data.get("bfaf", {}),
        dosage_schedule=data.get("dosage_schedule", {}),
        quantity=data.get("quantity", {}),
        prognosis=data.get("prognosis", ""),
        doctor_name=data.get("doctor_name", ""),
        today=datetime.today().strftime("%d-%m-%Y")
    )

    output_path = "/tmp/soap_note.pdf"
    with open(output_path, "wb") as f:
        pisa.CreatePDF(html, dest=f)
    return output_path
